# Generated by Django 4.1.5 on 2023-01-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_buffermodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buffermodel",
            name="id",
        ),
        migrations.RemoveField(
            model_name="hashaddress",
            name="id",
        ),
        migrations.AlterField(
            model_name="buffermodel",
            name="stock",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="hashaddress",
            name="user_id",
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
